app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return redirect('types');
})->name('index');



Route::resource('/types', 'TypeController');

Route::resource('/fields', 'FieldController');

Route::resource('/blocks', 'BlockController');

app/Block.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Block extends Model
{
    protected $fillable = [
    'name',
    'type_id'];

     public function type()
    {
        return $this->belongsTo('App\Type');
    }
}

app/Field.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Field extends Model
{
    protected $fillable = [
    'name',
    'type_id'];

     public function type()
    {
        return $this->belongsTo('App\Type');
    }
}

app/Type.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Type extends Model
{
    protected $fillable = ['name'];

  	public function blocks()
    {

        return $this->hasMany('App\Block');
    }

    public function types()
    {

        return $this->hasMany('App\Type');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/BlockController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;


class BlockController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $types = \App\Type::all();
        $blocks = \App\Block::all();
        
        $selectTypes = [];

        foreach ($types as $type) {
            $selectTypes[$type->id] = $type->name;
        }
        return view('blocks.index', compact('selectTypes','blocks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
        'name' => 'min:1|max:50|required',
        'type_id' => 'required|exists:types,id|integer'
        ]);

        $block = \App\Block::create($request->all()); 

        $type_name = \App\Type::find($block->type_id)->name;

        $result = [
            "name"   => $block->name,
            "id"  => $block->id,
            "type_name" => $type_name,
            "fieldUrl" => route('blocks.edit', $block->id),
            "deleteUrl" => route('blocks.destroy', $block->id),
        ];

        return $result;

        // return redirect()->route('blocks.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $block = \App\Block::find($id);

        return view('blocks.edit', compact('block'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
        $this->validate($request, [
        'name' => 'required|string|min:1|max:50',
        ]);

        $block = \App\Block::find($id)->update($request->all());
        return redirect()->route('blocks.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        \App\Block::find($id)->delete();
        return redirect()->route('blocks.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FieldController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

class FieldController extends Controller
{

    public function store(Request $request)
    {
       $this->validate($request, [
        'name' => 'min:1|max:50|required',
        'type_id' => 'required|exists:types,id|integer'
        ]);

        $field = \App\Field::create($request->all()); 

        $result = [
            "name"   => $field->name,
            "id"  => $field->id,
            "deleteUrl" => route('fields.destroy', $field->id),
        ];

        return $result;

    }

    public function show($id)
    {

        $fields = \App\Field::where('type_id', $id)->get();

        $type = \App\Type::find($id);

        return view('fields.index', compact('fields','type'));
    }

    public function destroy($id)
    {   
        $typeid = \App\Field::find($id)->type_id;
        \App\Field::find($id)->delete();
        return redirect()->route('fields.show', $typeid);
    }
}

app/Http/Controllers/TypeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

class TypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $types = \App\Type::all();
        return view('types.index', compact('types'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $this->validate($request, [
        'name' => 'required|min:1|max:50|'
        ]);

        $type = \App\Type::create($request->all());

        $result = [
            "name"   => $type->name,
            "id"  => $type->id,
            "fieldUrl" => route('fields.show', $type->id),
            "deleteUrl" => route('types.destroy', $type->id),
        ];

        return $result;
    
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        \App\Type::find($id)->delete();
        return redirect()->route('types.index');
    }
}

resources/views/blocks/edit.blade.php
@extends("layouts.app")
@section("content")

<div class="container">
	
	<div class="row">
		@if (count($errors) > 0)
		<div class="alert alert-danger">
			<ul>
				@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
				@endforeach
			</ul>
		</div>
		@endif

		<h1>Edit Block</h1>

		{{ Form::open(['route' => ["blocks.update", $block->id], 'method' => 'POST'] ) }}
		{{ Form::hidden('_method', 'PUT') }}
		

		{{ Form::label('name', 'Name:')}}
		{{ Form::text('name', $block->name, ['class'=>'form-control']) }}

		<hr>

		{{ form::submit('Save', ['class'=>'btn btn-primary spacebtn']) }}
		{{ Form::close() }}

		{{ Form::close() }}

	</div>
</div>
@endsection

resources/views/blocks/index.blade.php
@extends("layouts.app")
@section("content")

<div class="container">
	<div class="row">
		@if (count($errors) > 0)
			<div class="alert alert-danger">
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
		@endif

		<h1>Blocks</h1>                                                                                   
		<div class="table-responsive">          
			<table class="table">
				<thead>
					<tr>
						<th>ID</th>
						<th>Name</th>
						<th>Type</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					@foreach($blocks as $block)
						<tr>
							<td>{{ $block->id }}</td>
							<td>{{ $block->name }}</td>
							<td>{{ $block->type->name }}</td>
							<td>
								<a class="btn btn-primary" href="{{ route('blocks.edit', $block->id) }}">Edit</a>
								{{ Form::open(['route' => ['blocks.destroy', $block->id], 'method' => 'POST', 'class' => 'inline']) }}
								{{ Form::hidden('_method', 'DELETE') }}
								{{ form::submit('Delete', ['class'=>'btn btn-danger ']) }}
								{{ Form::close() }}
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
		</div>	

		<div class="form-inline form-group">
			<input type="text" id="block-name" class="form-control" name="name" placeholder="Name">
			{{Form::select('type_id', $selectTypes, '',['class'=>'form-control', 'id' => 'type-id']) }}
			<button class="btn btn-success" id="block-add">Add</button>
		</div>

	</div>
</div>

@endsection

resources/views/fields/index.blade.php
@extends("layouts.app")
@section("content")

<div class="container">
	<div class="row">
		@if (count($errors) > 0)
			<div class="alert alert-danger">
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
		@endif
		
		<h1>Fields of type "{{ $type->name }}"</h1>                                                                                   
		<div class="table-responsive">          
			<table class="table">
				<thead>
					<tr>
						<th>ID</th>
						<th>Name</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					@foreach($fields as $field)
						<tr>
							<td>{{ $field->id }}</td>
							<td>{{ $field->name }}</td>
							<td>
								{{ Form::open(['route' => ['fields.destroy', $field->id], 'method' => 'POST', 'class' => 'inline']) }}
								{{ Form::hidden('_method', 'DELETE') }}
								{{ form::submit('Delete', ['class'=>'btn btn-danger ']) }}
								{{ Form::close() }}
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
		</div>	

		<div class="form-inline form-group">
			<input type="text" id="field-name" class="form-control" placeholder="Name">
			<input type="hidden" id="field-type-id" class="form-control" value="{{ $type->id }}">
			<button class="btn btn-success" id="field-add">Add</button>
		</div>


	</div>
</div>

@endsection

resources/views/layouts/app.blade.php
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Inlusion</title>

	<script>
		var TOKEN = "{{ csrf_token() }}";
		var TYPE_ADD_URL = "{{route('types.store')}}";
		var BLOCK_ADD_URL = "{{route('blocks.store')}}";
		var FIELD_ADD_URL = "{{route('fields.store')}}";

	</script>


	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link href="{{ asset('css/app.css') }}" rel="stylesheet">

	<script type="text/javascript" src="https://code.jquery.com/jquery-3.1.1.min.js" defer></script>
	<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" defer></script>
	<script type="text/javascript" src="{{ asset('js/ajax.js') }}" defer></script>
	
	</head>

	<body>

		<!-- Navigation -->
		<nav class="navbar navbar-inverse" role="navigation">
			<div class="container">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{{route('index')}}">Inlusion</a>
				</div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li class="{{ Route::getFacadeRoot()->current()->uri() == 'types' ? 'active' : '' }}">
							<a href="{{route('types.index')}}">Types</a>
						</li>
						<li class="{{ Route::getFacadeRoot()->current()->uri() == 'blocks' ? 'active' : '' }}">
							<a href="{{route('blocks.index')}}">Blocks</a>
						</li>
					</ul>

				</div>
				<!-- /.navbar-collapse -->
			</div>
			<!-- /.container -->
		</nav>


		@yield('content')

<!-- Footer -->

    
</body>

</html>

resources/views/types/index.blade.php
@extends("layouts.app")
@section("content")

<div class="container">
	<div class="row">
		@if (count($errors) > 0)
			<div class="alert alert-danger">
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
		@endif
		
		<h1>Types</h1>                                                                                   
		<div class="table-responsive">          
			<table class="table">
				<thead>
					<tr>
						<th>ID</th>
						<th>Name</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					@foreach($types as $type)
						<tr>
							<td>{{ $type->id }}</td>
							<td>{{ $type->name }}</td>
							<td>
								<a class="btn btn-primary" href="{{ route('fields.show', $type->id) }}">Fields</a>
								{{ Form::open(['route' => ['types.destroy', $type->id], 'method' => 'POST', 'class' => 'inline']) }}
								{{ Form::hidden('_method', 'DELETE') }}
								{{ form::submit('Delete', ['class'=>'btn btn-danger ']) }}
								{{ Form::close() }}
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
		</div>	

		<div class="form-inline form-group">
			<input type="text" id="type-name" class="form-control" name="name" placeholder="Name">
			<button class="btn btn-success" id="type-add">Add</button>
		</div>

	</div>
</div>

@endsection